### ISSUE TITLE
[1.20.1] Crash on Load

### ISSUE THREAD

**Issue by Reshy** [TeamGalena/copperative#47]
### What happened?

Log:  https://cdn.discordapp.com/attachments/249267900953788417/1218506381364297779/message.txt?ex=6607e980&is=65f57480&hm=e7649d28f6d177c809c19a013d2d195882a56873026c04fc24e7902199ff6b97&

Crash:  https://pastebin.com/DZbv8BZd

### Mod Version

Copperative 1.20.1--1.1.0.jar

### Minecraft Version

1.20

### Relevant log output

```Shell
§7java.lang.NullPointerException: Registry Object not present: copperative:copper_bricks
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:118) ~[javafmllanguage-1.20.1-47.2.20.jar%23866!/:?]
		at net.minecraftforge.fml.ModLoader.lambda$postEventWithWrapInModOrder$33(ModLoader.java:346) ~[fmlcore-1.20.1-47.2.20.jar%23865!/:?]
		at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
		at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[fmlcore-1.20.1-47.2.20.jar%23865!/:?]
		at net.minecraftforge.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:344) ~[fmlcore-1.20.1-47.2.20.jar%23865!/:?]
		at net.minecraftforge.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:337) ~[fmlcore-1.20.1-47.2.20.jar%23865!/:?]
		at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:329) ~[forge-1.20.1-47.2.20-universal.jar%23869!/:?]
		at net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25) ~[forge-1.20.1-47.2.20-universal.jar%23869!/:?]
		at net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:217) ~[fmlcore-1.20.1-47.2.20.jar%23865!/:?]
		at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:209) ~[fmlcore-1.20.1-47.2.20.jar%23865!/:?]
		at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
		at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:209) ~[fmlcore-1.20.1-47.2.20.jar%23865!/:?]
		at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.20.jar%23865!/:?]
		at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
		at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.20.jar%23865!/:?]
		at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:70) ~[forge-1.20.1-47.2.20-universal.jar%23869!/:?]
		at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:90) ~[forge-1.20.1-47.2.20-universal.jar%23869!/:?]
		at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:70) ~[forge-1.20.1-47.2.20-universal.jar%23869!/:?]
		at net.minecraft.client.Minecraft.<init>(Minecraft.java:459) ~[client-1.20.1-20230612.114412-srg.jar%23864!/:?]
		at net.minecraft.client.main.Main.main(Main.java:182) ~[forge-47.2.20.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?]
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?]
		at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	Caused by: java.lang.NullPointerException: Registry Object not present: copperative:copper_bricks
		at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:572) ~[forge-1.20.1-47.2.20-universal.jar%23869!/:?]
		at galena.copperative.index.CConversions.blockMapFromArray(CConversions.java:107) ~[Copperative%201.20.1--1.1.0.jar%23584!/:1.1.0]
		at galena.copperative.index.CConversions.lambda$static$0(CConversions.java:18) ~[Copperative%201.20.1--1.1.0.jar%23584!/:1.1.0]
		at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar%23109!/:?]
		at galena.copperative.index.CConversions.getUnweatheredVersion(CConversions.java:66) ~[Copperative%201.20.1--1.1.0.jar%23584!/:1.1.0]
		at galena.copperative.index.CConversions.getFirst(CConversions.java:81) ~[Copperative%201.20.1--1.1.0.jar%23584!/:1.1.0]
		at galena.copperative.config.CommonConfig.test(CommonConfig.java:96) ~[Copperative%201.20.1--1.1.0.jar%23584!/:1.1.0]
		at galena.copperative.config.CommonConfig.isOverwriteEnabled(CommonConfig.java:103) ~[Copperative%201.20.1--1.1.0.jar%23584!/:1.1.0]
		at net.minecraft.world.level.block.Block.handler$dlo000$copperative$modifySoundType(Block.java:2137) ~[client-1.20.1-20230612.114412-srg.jar%23864!/:?]
		at net.minecraft.world.level.block.Block.m_49962_(Block.java:458) ~[client-1.20.1-20230612.114412-srg.jar%23864!/:?]
		at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60827_(BlockBehaviour.java:868) ~[client-1.20.1-20230612.114412-srg.jar%23864!/:?]
		at com.mgen256.al.blocks.ALLamp.createProps(ALLamp.java:48) ~[additional_lights-1.20.1-2.1.7.jar%23520!/:1.20.1-2.1.7]
		at com.mgen256.al.blocks.ALLamp.<init>(ALLamp.java:57) ~[additional_lights-1.20.1-2.1.7.jar%23520!/:1.20.1-2.1.7]
		at com.mgen256.al.ModBlockList.lambda$static$0(ModBlockList.java:25) ~[additional_lights-1.20.1-2.1.7.jar%23520!/:1.20.1-2.1.7]
		at com.mgen256.al.ModBlockList.lambda$register$173(ModBlockList.java:232) ~[additional_lights-1.20.1-2.1.7.jar%23520!/:1.20.1-2.1.7]
		at net.minecraftforge.registries.DeferredRegister.lambda$addEntries$1(DeferredRegister.java:386) ~[forge-1.20.1-47.2.20-universal.jar%23869!/:?]
		at net.minecraftforge.registries.RegisterEvent.register(RegisterEvent.java:59) ~[forge-1.20.1-47.2.20-universal.jar%23869!/:?]
		at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:386) ~[forge-1.20.1-47.2.20-universal.jar%23869!/:?]
		at net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:328) ~[forge-1.20.1-47.2.20-universal.jar%23869!/:?]
		at net.minecraftforge.registries.__EventDispatcher_handleEvent_RegisterEvent.invoke(.dynamic) ~[forge-1.20.1-47.2.20-universal.jar%23869!/:?]
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:114) ~[javafmllanguage-1.20.1-47.2.20.jar%23866!/:?]
		... 34 more
	Suppressed: net.minecraftforge.fml.ModLoadingException: Additional Lights (additional_lights) encountered an error during the common_setup event phase
```

**Comment by VratPIR** [comment]
Still relevant. Same error - same crash_log

**Comment by mgrosseh** [comment]
see https://github.com/TeamGalena/copperative/issues/54#issue-2847244420 for fix-ish and detailed bug explanation

**Comment by autumnly24** [comment]
> see [#54 (comment)](https://github.com/TeamGalena/copperative/issues/54#issue-2847244420) for fix-ish and detailed bug explanation

I'm getting the same error as this issue but I don't have any of the mods mentioned in that other issue you linked (other than copperative obviously)
