### ISSUE TITLE
[1.20.1] Crash with Create

### ISSUE THREAD

**Issue by OhHeyItsK** [TeamGalena/copperative#48]
### What happened?

Crashed on load

### Mod Version

1.1.0

### Minecraft Version

1.20

### Relevant log output

```Shell
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:336) ~[?:?] {re:mixin}
	at com.tterrag.registrate.util.entry.RegistryEntry.get(RegistryEntry.java:114) ~[Registrate-MC1.20-1.3.3.jar%23993!/:?] {re:mixin,re:classloading}
	at com.simibubi.create.foundation.block.CopperBlockSet.lambda$new$6(CopperBlockSet.java:99) ~[create-1.20.1-0.5.1.f.jar%23607!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.block.CopperRegistries.lambda$inject$0(CopperRegistries.java:55) ~[create-1.20.1-0.5.1.f.jar%23607!/:0.5.1.f] {re:classloading}
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:576) ~[guava-31.1-jre.jar%23109!/:?] {}
	at com.simibubi.create.foundation.block.CopperRegistries.lambda$inject$1(CopperRegistries.java:54) ~[create-1.20.1-0.5.1.f.jar%23607!/:0.5.1.f] {re:classloading}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar%23109!/:?] {}
	at net.minecraft.world.level.block.WeatheringCopper.m_154904_(WeatheringCopper.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23892!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:copperative.mixins.json:WeatheringCopperMixin,pl:mixin:APP:zeta_forge.mixins.json:WeatheringCopperMixin,pl:mixin:A}
	at net.minecraft.world.level.block.WeatheringCopperFullBlock.m_6724_(WeatheringCopperFullBlock.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23892!/:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60611_(BlockBehaviour.java:513) ~[client-1.20.1-20230612.114412-srg.jar%23892!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:supplementaries-common.mixins.json:BlockBehaviourPlanterMixin,pl:mixin:APP:fruitsdelight.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:APP:arc-common.mixins.json:MixinBlockStateBase,pl:mixin:APP:twigs.mixins.json:BlockStateBaseMixin,pl:mixin:APP:etcetera.mixins.json:AbstractBlockStateMixin,pl:mixin:A}
	at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:461) ~[forge-1.20.1-47.2.0-universal.jar%23897!/:?] {re:classloading}
	at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:623) ~[forge-1.20.1-47.2.0-universal.jar%23897!/:?] {re:mixin,re:classloading,pl:mixin:APP:puzzleslib.forge.mixins.json:accessor.ForgeRegistryForgeAccessor,pl:mixin:A}
	at net.minecraftforge.registries.GameData.lambda$revertTo$11(GameData.java:299) ~[forge-1.20.1-47.2.0-universal.jar%23897!/:?] {re:mixin,re:classloading,pl:mixin:APP:supermartijn642corelib.mixins.json:GameDataMixin,pl:mixin:A}
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:576) ~[guava-31.1-jre.jar%23109!/:?] {}
	at net.minecraftforge.registries.GameData.revertTo(GameData.java:299) ~[forge-1.20.1-47.2.0-universal.jar%23897!/:?] {re:mixin,re:classloading,pl:mixin:APP:supermartijn642corelib.mixins.json:GameDataMixin,pl:mixin:A}
	at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:358) ~[forge-1.20.1-47.2.0-universal.jar%23897!/:?] {re:mixin,re:classloading,pl:mixin:APP:supermartijn642corelib.mixins.json:GameDataMixin,pl:mixin:A}
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25) ~[forge-1.20.1-47.2.0-universal.jar%23897!/:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:217) ~[fmlcore-1.20.1-47.2.0.jar%23893!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:209) ~[fmlcore-1.20.1-47.2.0.jar%23893!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:209) ~[fmlcore-1.20.1-47.2.0.jar%23893!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.0.jar%23893!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.0.jar%23893!/:?] {}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:70) ~[forge-1.20.1-47.2.0-universal.jar%23897!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:90) ~[forge-1.20.1-47.2.0-universal.jar%23897!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:70) ~[forge-1.20.1-47.2.0-universal.jar%23897!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:459) ~[client-1.20.1-20230612.114412-srg.jar%23892!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:pickupnotifier.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:the_bumblezone-common.mixins.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:brewery-common.mixins.json:rope.PickMixin,pl:mixin:APP:travelerstitles.mixins.json:MinecraftClientTickMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:immersive_armors.mixins.json:MixinMinecraftClient,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraft,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixin.dynamic_asset_generator.json:MinecraftMixin,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:quark.mixins.json:client.MinecraftMixin,pl:mixin:APP:mixins.essential.json:client.Mixin_RunEssentialTasks,pl:mixin:APP:mixins.essential.json:client.MixinMinecraft,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_FixKeybindUnpressedInEmoteWheel,pl:mixin:APP:mixins.essential.json:client.gui.Mixin_RecalculateMenuScale,pl:mixin:APP:mixins.essential.json:compatibility.vanilla.Mixin_WorkaroundBrokenFramebufferBlitBlending,pl:mixin:APP:mixins.essential.json:feature.emote.Mixin_AllowMovementDuringEmoteWheel_HandleKeybinds,pl:mixin:APP:mixins.essential.json:feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
```

**Comment by mgrosseh** [comment]
see https://github.com/TeamGalena/copperative/issues/54#issue-2847244420 for fix-ish and detailed bug explanation
